version: "3.8"
services:
  serivce1:
    build: ./service1
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  serivce2:
    build: ./service2
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  serivce3:
    build: ./service3
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  serivce4:
    build: ./service4
    ports:
      - target: 5004
        published: 5004
        protocol: tcp