version: "3.8"
services:
  service1:
    image: jmiller2612/prizepipeline_service1:1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
  service2:
    image: jmiller2612/prizepipeline_service2:1
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  service3:
    image: jmiller2612/prizepipeline_service3:1
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  service4:
    image: jmiller2612/prizepipeline_service4:1
    ports:
      - target: 5004
        published: 5004
        protocol: tcp