version: "3.8"
services:
  service1:
    build: jmiller2612/prizepipeline_service1:1
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service2:
    build: jmiller2612/prizepipeline_service2:1
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  service3:
    build: jmiller2612/prizepipeline_service3:1
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  service4:
    build: jmiller2612/prizepipeline_service4:1
    ports:
      - target: 5004
        published: 5004
        protocol: tcp