---
# tasks file for loadbalancer
- name: install nginx apt
  become: true
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true
- name: started correctly?
  become: true
  service:
    name: nginx
    state: started
- name: configure nginx
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: 'reload nginx'